(define (evalbool l)
  (cond
    ((eq? l 'true) #t)
    ((eq? l 'false) #f)
    ((eq? (car l) 'and)
     (and (evalbool (cadr l)) (evalbool (caddr l)))
    )
    ((eq? (car l) 'or)
     (or (evalbool (cadr l)) (evalbool (caddr l)))
    )
    ((eq? (car l) 'not)
     (not (evalbool (cadr l)))
    )
    (else #f)
  )
)

(display (evalbool '(and (not 'true) (or 'false 'true))))
(newline)
(display (evalbool '(or (not 'true) (or 'false 'true))))
(newline)